/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_ipstack_net_tuntap_TuntapSocket */

#ifndef _Included_io_ipstack_net_tuntap_TuntapSocket
#define _Included_io_ipstack_net_tuntap_TuntapSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_ipstack_net_tuntap_TuntapSocket
 * Method:    open
 * Signature: (ZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_ipstack_net_tuntap_TuntapSocket_open
  (JNIEnv *, jobject, jboolean, jstring);

/*
 * Class:     io_ipstack_net_tuntap_TuntapSocket
 * Method:    openDev
 * Signature: (ZLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_ipstack_net_tuntap_TuntapSocket_openDev
  (JNIEnv *, jobject, jboolean, jstring, jstring);

/*
 * Class:     io_ipstack_net_tuntap_TuntapSocket
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_ipstack_net_tuntap_TuntapSocket_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_ipstack_net_tuntap_TuntapSocket
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_io_ipstack_net_tuntap_TuntapSocket_write
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     io_ipstack_net_tuntap_TuntapSocket
 * Method:    read
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_io_ipstack_net_tuntap_TuntapSocket_read
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
